version = 0.1

[default.deploy.parameters]
stack_name = "compliance-logger"
resolve_s3 = true
s3_prefix = "compliance-logger"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
