AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Compliance Logger – logs Config rule violations and sends high-severity alerts

Globals:
  Function:
    Runtime: python3.12   # change from 3.11 to 3.12
    Timeout: 60
    MemorySize: 512
    Tracing: Active

Resources:
  ComplianceLoggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Description: Logs compliance violations and optionally notifies via SNS
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref ComplianceAlertsTopic
      Policies:
        - AWSLambdaBasicExecutionRole
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ComplianceAlertsTopic.TopicName

  ComplianceAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: compliance-alerts

Outputs:
  FunctionArn:
    Description: ARN of Compliance Logger Lambda
    Value: !GetAtt ComplianceLoggerFunction.Arn
    Export:
      Name: ComplianceLoggerFunctionArn
